name: Daily Scraper

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 13 * * *'  # Runs every day at 1 PM UTC

jobs:
  scrape_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the scraper
        run: |
          python alltogethor.py  # Replace with your script name

      # New steps to commit and push the updated files
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add urbium.json urbium.csv  # Add your JSON and CSV file names here
          git commit -m "Update data files [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
