name: Daily Scraper

on:
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

  # Schedule the scraper to run at 1 PM UTC every day
  schedule:
    - cron: '0 13 * * *'

jobs:
  scrape_job:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the scraping script
      - name: Run the scraper
        run: |
          python alltogethor.py  # Replace with the name of your Python script

